
version: "3.8"

services: 
  mbhClinicianService:
    image: mbhclinicianservice
    build:
      context: .
      dockerfile: MBH.Clinician/src/MBH.Clinician.Service/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
        - mongo
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "ASPNETCORE_URLS=https://+;http://+"
       - ASPNETCORE_Kestrel__Certificates__Default__Password=password
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/docker.pfx
    volumes:
        - ~/.aspnet/https:/https
  mbhApplicationService:
          image: mbhapplicationservice
          build:
            context: .
            dockerfile: MBH.Application/src/MBH.Application.Service/Dockerfile
          ports:
            - 5004:80
            - 5005:443
          depends_on:
              - mongo
          environment:
             - ASPNETCORE_ENVIRONMENT=Development
             - "ASPNETCORE_URLS=https://+;http://+"
             - ASPNETCORE_Kestrel__Certificates__Default__Password=password
             - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/docker.pfx
          volumes:
              - ~/.aspnet/https:/https
  dynamodb-local:
    command: -jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_REGION=localhost
    ports:
      - 8000:8000
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
volumes: 
  mongodbdata:
  rabbitmqdata: