
version: "3.8"

services: 
  mbhlabtestservice:
    image: mbhlabtestservice
    build:
      context: .
      dockerfile: ../MBH.LabTest/src/MBH.LabTest.Service/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
        - mongo
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "ASPNETCORE_URLS=https://+;http://+"
       - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mycertificatename.pfx
    volumes:
        - ~/.aspnet/https:/https
  dynamodb-local:
    command: -jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
volumes: 
  mongodbdata:
  rabbitmqdata: